# Generated by Django 5.1.4 on 2024-12-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
