# Generated by Django 5.1.4 on 2024-12-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_url_date_alter_url_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='url_data',
        ),
    ]
