# Generated by Django 5.1.4 on 2024-12-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_url_url_url_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url_data',
            new_name='url',
        ),
    ]
